# Generated by Django 3.2.21 on 2023-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('aadharnumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('symptoms', models.TextField()),
                ('ename', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=30)),
                ('emergencynumber', models.CharField(max_length=10)),
            ],
        ),
    ]
