# Generated by Django 3.2.23 on 2023-12-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
