# Generated by Django 3.2.23 on 2023-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='Aname',
            field=models.CharField(default='Aname', max_length=255),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='Bname',
            field=models.CharField(default='Bname', max_length=255),
        ),
    ]
