# Generated by Django 3.2.23 on 2023-12-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20231220_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
