# Generated by Django 3.2.23 on 2023-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phoneNo', models.CharField(max_length=15)),
                ('appointment', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
            ],
        ),
    ]
